### PR TITLE
Summary:  add a Semigroup instance (GHC 8.4.1 compat)

### PR DESCRIPTION
**Pull request by deepfire**
Tested on GHC 8.4.1 and 8.0.2.

### CODE REVIEW

**Comment by ocharles** [comment]
Thank you!

**Comment by asr** [comment]
@ocharles, thanks for merging. Could you make a release, please?

**Comment by ocharles** [comment]
Yea, I need to bump some bounds for tasty too. Will try and get these all
out tomorrow, sorry for the delay.

**Comment by ocharles** [comment]
Released.

**Comment by asr** [comment]
Thanks!

**Pull request merged**
